pool:
  name: n-pool   # Linux self-hosted

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- script: dotnet restore
- script: dotnet build --configuration Release
- script: dotnet test --configuration Release
